import PubSub from "pubsub-js"
import { pubSubTokens } from "../pubSubTokens.js"
import { initDiv } from "../utils/domComponents.js"
import CellDom from "./CellDom.js"
import ShipDom from "./ShipDom.js"
import MissMarkDom from "./MissMarkDom.js"
import HitMarkDom from "./HitMarkDom.js"

const blockName = "gameboard"
const aimingClass = "aiming"

const animationInitialStateClass = "initial-state"
const animationDuration = 200 // ms

// set the animation duration css property
document.documentElement.style.setProperty(
	"--time-animation",
	`${animationDuration}ms`
)

export default class GameboardDom {
	#gameboard
	#div
	#attackCallback
	#cells
	#fleetDom
	#deployedFleetDomShown
	#deployedFleetAnimationOn

	constructor(gameboard, canBeModified = false) {
		this.#gameboard = gameboard
		this.#cells = new Map()
		this.#div = this.#initGameboardDiv(gameboard)
		this.#div.obj = this

		this.#fleetDom = new Map()
		this.#initFleet()
		this.#deployedFleetDomShown = false
		this.#deployedFleetAnimationOn = false

		if (canBeModified) {
			this.#setEditCallbacks()
		}
	}

	// getters
	get gameboard() {
		return this.#gameboard
	}

	get div() {
		return this.#div
	}

	async showAttackOutcome(coords, outcome) {
		// the function is async, and awaits for the hit/miss mark show animation, if any
		const cellDom = this.#cells.get(coords.join(","))
		cellDom.setAttackStatus()

		const outcomeMarkDom = outcome.isHit
			? new HitMarkDom(coords)
			: new MissMarkDom(coords)
		this.#div.append(outcomeMarkDom.div)

		await triggerAnimation(outcomeMarkDom.div)

		if (outcome.isSunk) {
			const shipName = outcome.sunkShip.name
			const shipObj = this.#fleetDom.get(shipName)
			shipObj.makeItSunk()
			await this.#showShip(shipObj)
		}
		PubSub.publish(pubSubTokens.attackOutcomeShown, { coords, outcome })
	}

	enableAiming() {
		this.#div.classList.add(aimingClass)
		this.#attackCallback = this.#getAttackCoordsOnClickCallback.bind(this)
		this.#div.addEventListener("click", this.#attackCallback)
	}

	#createShipDom(shipName) {
		const shipObj = new ShipDom(
			shipName,
			...this.#gameboard.getShipPosition(shipName)
		)
		return shipObj
	}

	async #showShip(shipObj) {
		// the function is async, and awaits for the ship show animation, if any
		this.#div.append(shipObj.div)
		await triggerAnimation(shipObj.div)
	}

	async #hideShip(shipObj) {
		// the function is async, and awaits for the ship show animation, if any
		await triggerAnimation(shipObj.div, true)
		// wait for the animation end before removing it
		this.#div.removeChild(shipObj.div)
	}

	#initFleet() {
		// All fleets already have coordinates generated by randomShipsPlacement()
		this.#gameboard.fleet.forEach((shipName) => {
			const shipObj = this.#createShipDom(shipName)
			this.#fleetDom.set(shipName, shipObj)
		})
	}

	// the function is async, and awaits for all the ship show animations, if any
	async showDeployedFleet() {
		// do nothing if there is an animation ongoing or the fleet is already shown
		if (!this.#deployedFleetDomShown && !this.#deployedFleetAnimationOn) {
			this.#deployedFleetAnimationOn = true

			// save promises returned by #showShip to eventually wait for their resolution
			const promiseArray = []

			this.#gameboard.deployedFleet.forEach((shipName) => {
				const shipObj = this.#fleetDom.get(shipName)
				promiseArray.push(this.#showShip(shipObj)) // returns a promise
			})

			await Promise.all(promiseArray)

			this.#deployedFleetDomShown = true
			this.#deployedFleetAnimationOn = false
		}
	}

	// the function is async, and awaits for all the ship show animations, if any
	async hideDeployedFleet() {
		// do nothing if there is an animation ongoing or the fleet is already hidden
		if (this.#deployedFleetDomShown && !this.#deployedFleetAnimationOn) {
			this.#deployedFleetAnimationOn = true

			// save promises returned by #showShip to eventually wait for their resolution
			const promiseArray = []
			this.#gameboard.deployedFleet.forEach((shipName) => {
				const shipObj = this.#fleetDom.get(shipName)
				promiseArray.push(this.#hideShip(shipObj)) // returns a promise
			})

			await Promise.all(promiseArray)

			this.#deployedFleetDomShown = false
			this.#deployedFleetAnimationOn = false
		}
	}

	toggleDeployedFleet() {
		if (this.#deployedFleetDomShown) {
			this.hideDeployedFleet()
		} else {
			this.showDeployedFleet()
		}
	}

	async updateDeployedFleet() {
		await this.hideDeployedFleet()

		// change position of shipDom objects
		this.#gameboard.fleet.forEach((shipName) => {
			const shipObj = this.#fleetDom.get(shipName)
			shipObj.updatePosition(...this.#gameboard.getShipPosition(shipName))
		})

		await this.showDeployedFleet()
	}

	async updateDeployedShip(shipName) {
		const shipObj = this.#fleetDom.get(shipName)

		await this.#hideShip(shipObj)

		// change position of shipDom objects
		shipObj.updatePosition(...this.#gameboard.getShipPosition(shipName))

		await this.#showShip(shipObj)
	}

	#initGameboardDiv(gameboard) {
		const div = initDiv(blockName)

		// Forced grid appearance
		div.style.display = "grid"
		div.style.aspectRatio = `${gameboard.nCols}/${gameboard.nRows}`
		div.style.gridTemplateColumns = `repeat(${gameboard.nCols}, minmax(0, 1fr))`
		div.style.gridTemplateRows = `repeat(${gameboard.nRows}, minmax(0, 1fr))`

		const cells = gameboard.cells
		cells.forEach((column) => {
			column.forEach((cell) => {
				const cellDom = new CellDom(cell)
				this.#cells.set(cell.coords.join(","), cellDom)
				div.append(cellDom.div)
			})
		})

		return div
	}

	#getCellOnClick(e) {
		const targetClassList = e.target.classList
		if (![...targetClassList].includes("cell")) {
			// Clicking the element underneath an overlay
			const origDisplay = e.target.style.display
			e.target.style.display = "none"
			document.elementFromPoint(e.clientX, e.clientY).click()
			e.target.style.display = origDisplay
			return
		}

		e.preventDefault()

		const cellDiv = e.target
		return cellDiv.obj.cell
	}

	#getAttackCoordsOnClickCallback(e) {
		// We have subscribed to one event listener for the gameboard:
		// We need to retrieve the appropriate cell
		const cell = this.#getCellOnClick(e)

		if (!cell.hasBeenAttacked()) {
			// exit aiming mode
			this.#div.classList.remove(aimingClass)
			this.#div.removeEventListener("click", this.#attackCallback)
		}

		PubSub.publish(pubSubTokens.attackCoordsAcquired, cell.coords)
	}

	#setEditCallbacks() {
		this.#div.addEventListener(
			"click",
			this.#rotateShipOnClickCallback.bind(this)
		)
	}

	#rotateShipOnClickCallback(e) {
		const cell = this.#getCellOnClick(e)

		if (!cell) {
			return
		}

		if (!cell.hasShip()) {
			console.log("No ship to rotate here...")
			return
		}

		const shipName = cell.getShip().name
		const centerOfRotation = cell.coords
		console.log(`I'm rotating ship ${shipName} around [${centerOfRotation}]...`)

		this.#gameboard.rotateShip(shipName, centerOfRotation)
		this.updateDeployedShip(shipName)
	}
}

async function triggerAnimation(div, hide = false) {
	// this uses a trick to trigger the animation on the element

	hide
		? div.classList.remove(animationInitialStateClass)
		: div.classList.add(animationInitialStateClass)

	await new Promise((resolve) => requestAnimationFrame(resolve))
	await new Promise((resolve) =>
		setTimeout(() => {
			div.classList.toggle(animationInitialStateClass)
			resolve()
		}, 0)
	)

	// wait for the animation to end before removing it
	return new Promise((resolve) => setTimeout(resolve, animationDuration))
}
